export function flag(p) { return p >= 75 ? "#2E7D32" : p >= 50 ? "#E0A800" : "#C0392B"; }
export function track(p) { return p >= 75 ? "#E3EFE4" : p >= 50 ? "#FBF0D6" : "#FBE3DC"; }
export function statusWord(p) { return p >= 75 ? "On track" : p >= 50 ? "Needs watching" : "Delay"; }
export const nf = (n) => Math.round(n).toLocaleString("en-IN");

function toDateStr(d) {
  return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
}

// Default date-range: 1st of the current month through today (local time --
// avoids the date rolling to the wrong day that toISOString()'s UTC
// conversion would cause near midnight).
export function defaultRange() {
  const now = new Date();
  return { from: toDateStr(new Date(now.getFullYear(), now.getMonth(), 1)), to: toDateStr(now) };
}

const DATE_RANGE_STORAGE_KEY = "pmoDateRange";

// Reads a previously-picked date range back from localStorage (shared across
// Summary/Process/Comparative, so a choice on one page carries to the
// others and survives a refresh), falling back to defaultRange() if nothing
// was saved yet or localStorage is unavailable (privacy mode, etc.).
export function loadPersistedRange() {
  try {
    const raw = localStorage.getItem(DATE_RANGE_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed.from === "string" && typeof parsed.to === "string") return parsed;
    }
  } catch {
    // Fall through to the default.
  }
  return defaultRange();
}

export function savePersistedRange(range) {
  try {
    localStorage.setItem(DATE_RANGE_STORAGE_KEY, JSON.stringify(range));
  } catch {
    // Best-effort only.
  }
}

/* NCR-level roll-ups. Numerators are summed across Delhi, UP, Rajasthan and Haryana
   from the same state figures the six state dashboards use. */
export const INITIATIVES = [
  { key: "parivartan", name: "PARIVARTAN", ministry: "MORTH", owner: "MoRTH · NCRPB",
    splits: [{ key: "trucks", label: "Trucks", mult: 0.82, perf: 1.06 }, { key: "buses", label: "Buses", mult: 0.18, perf: 0.72 }],
    footNote: "Source and ownership are shown when a metric is opened.",
    l1: [
      { seg: "trucks", name: "% of pre-BS VI vehicles converted (Trucks)", num: 6401, den: 16000,
        formula: "No. of trucks converted (scrapped or sold) ÷ No. of target trucks",
        rationale: "Track the scheme disposal rate for trucks.", agency: "MoRTH", source: "Beneficiary portal",
        numL: "trucks converted", denL: "target trucks",
        context: ["Beneficiary registration", "Scrap or sell", "Truck procured"], active: 1 },
      { seg: "buses", name: "% of pre-BS VI vehicles converted (Buses)", num: 1099, den: 3580,
        formula: "No. of buses converted (scrapped or sold) ÷ No. of target buses",
        rationale: "Track the scheme disposal rate for buses.", agency: "MoRTH", source: "Beneficiary portal",
        numL: "buses converted", denL: "target buses",
        context: ["Beneficiary registration", "Scrap or sell", "Bus procured"], active: 1 }
    ],
    stages: [
      { n: 1, label: "Registration", hint: "Beneficiary registers on the portal" },
      { n: 2, label: "Scrap vs sell", hint: "Decision point: scrap at RVSF or sell outside NCR" },
      { n: 3, label: "Loan", hint: "Loan application, approval and disbursal" },
      { n: 4, label: "Interest subvention", hint: "Monthly interest subvention claims and payments" },
      { n: 5, label: "One-time claim", hint: "One-time claim approved by MoRTH and paid by NCRPB" },
      { n: 6, label: "Fuel voucher", hint: "Fuel voucher claims approved by MoPNG and paid by NCRPB" }
    ],
    metrics: [
      { stage: 1, stageLabel: "Registration", name: "% registered on portal", num: 11240, den: 19580,
        formula: "No. of registered vehicles ÷ No. of target vehicles", rationale: "Track scheme adoption.",
        agency: "MoRTH", source: "Beneficiary portal", numL: "registered", denL: "target vehicles",
        context: ["Beneficiary registration", "Decision: scrap vs sell", "Scrap at RVSF"], active: 0 },
      { stage: 2, stageLabel: "Scrap vs sell", name: "% CoD generated by RVSF", num: 3180, den: 4120,
        formula: "No. of CoDs generated by RVSF ÷ No. of scrapping applications", rationale: "Identify delays in scrapping at RVSFs.",
        agency: "RVSF", source: "V-Scrap", numL: "CoDs generated", denL: "scrapping applications",
        context: ["Decision: scrap vs sell", "Scrap at RVSF", "CoD issued"], active: 1,
        glossary: "RVSF — Registered Vehicle Scrapping Facility. CoD — Certificate of Deposit, issued on scrapping." },
      { stage: 2, stageLabel: "Scrap vs sell", name: "% sell outside NCR process completed by RTO", num: 2410, den: 3380,
        formula: "No. of selling applications (NOC & TOs) approved by RTO ÷ No. of selling applications",
        rationale: "Track delays in NOC and Transfer of Ownership at RTOs.", agency: "RTO", source: "VAHAN",
        numL: "approved", denL: "selling applications",
        context: ["Decision: scrap vs sell", "Sell outside NCR", "NOC + Transfer of Ownership"], active: 2,
        glossary: "NOC — No Objection Certificate. TO — Transfer of Ownership." },
      { stage: 3, stageLabel: "Loan", name: "Share of loans approved", num: 4860, den: 6940,
        formula: "No. of approved loan applications ÷ No. of loan applications", rationale: "Monitor post-sanction approvals.",
        agency: "Bank / NBFC", source: "Nodal bank portal", numL: "approved", denL: "loan applications",
        context: ["Loan application & sanction", "OEM discount", "Truck / bus procured"], active: 0 },
      { stage: 3, stageLabel: "Loan", name: "Share of loans disbursed", num: 3120, den: 4860,
        formula: "No. of loan disbursements ÷ No. of approved loan applications", rationale: "Track post-approval payment disbursal.",
        agency: "Bank / NBFC", source: "Nodal bank portal", numL: "disbursed", denL: "approved applications",
        context: ["Loan approved", "Loan disbursed", "Truck / bus procured"], active: 1 },
      { stage: 4, stageLabel: "Interest subvention", name: "% interest subvention approved by Nodal bank", num: 2190, den: 3120,
        formula: "No. of approved interest subvention claims ÷ No. of approved loan applications",
        rationale: "Track Nodal Bank approval delays.", agency: "Nodal Bank", source: "Nodal bank portal",
        numL: "claims approved", denL: "approved loans",
        context: ["Lender submits claim", "Nodal Bank approves", "NCRPB releases payment"], active: 1,
        glossary: "Interest subvention is 5% per annum on outstanding principal, paid monthly for five years." },
      { stage: 4, stageLabel: "Interest subvention", name: "% interest subvention disbursed by NCRPB", num: 1240, den: 2190,
        formula: "No. of payments released by NCRPB ÷ No. of approved claims by Nodal bank",
        rationale: "Track NCRPB approval delays.", agency: "NCRPB", source: "Not yet identified",
        numL: "released", denL: "claims approved",
        context: ["Nodal Bank approves", "NCRPB approves", "PFMS credits loan account"], active: 1 },
      { stage: 5, stageLabel: "One-time claim (OTC)", name: "% one-time claims (OTC) disbursed by NCRPB", num: 640, den: 1180,
        formula: "No. of OTC payments released by NCRPB ÷ No. of approved OTC claims by MoRTH",
        rationale: "Track OTC approvals by NCRPB.", agency: "NCRPB", source: "Not yet identified",
        numL: "released", denL: "claims approved",
        context: ["Vehicle registered", "MoRTH approves claim", "NCRPB releases payment"], active: 2,
        glossary: "OTC — One-Time Claim, disbursed to EV buyers at a value equivalent to the fuel voucher." },
      { stage: 6, stageLabel: "Fuel voucher", name: "% fuel voucher payments released by NCRPB", num: 1460, den: 3240,
        formula: "No. of payments released by NCRPB ÷ No. of approved fuel voucher claims by MoPNG",
        rationale: "Track NCRPB payment backlog for fuel vouchers.", agency: "NCRPB", source: "Not yet identified",
        numL: "released", denL: "claims approved",
        context: ["OMC / CGD validate usage", "MoPNG validates data", "NCRPB releases payment"], active: 2 }
    ] },

  { key: "green-contribution", name: "Green Contribution", ministry: "MORTH", owner: "MoRTH · NHAI",
    note: "Programme under design phase",
    footNote: "Metric definitions are being finalised; no data feed is live yet.",
    l1: [{ name: "% of tolls collecting Green Contribution", num: 0, den: 0,
      formula: "No. of tolls collecting Green Contribution ÷ No. of tolls in NCR",
      rationale: "Track roll-out of the Green Contribution levy across NCR toll plazas.",
      agency: "NHAI", source: "To be identified", numL: "tolls collecting", denL: "tolls in NCR",
      context: ["Levy notified", "Toll systems configured", "Contribution collected"], active: 0,
      glossary: "The programme is in design; L2 process metrics will be added once the levy design is notified." }],
    stages: [{ n: 1, label: "Design", hint: "Levy design and notification in progress" }],
    metrics: [] },

  { key: "mrs", name: "Mechanized Road Sweeping", ministry: "MOHUA", owner: "MoHUA · ULBs · CAQM",
    splits: [{ key: "all", label: "All road widths", mult: 1, perf: 1 }, { key: "w15", label: "Above 15 m", mult: 0.34, perf: 1.28 },
      { key: "w10", label: "10–15 m", mult: 0.41, perf: 0.94 }, { key: "w0", label: "Below 10 m", mult: 0.25, perf: 0.52 }],
    footNote: "All MRS metrics are tracked by road width. API feeds to be sought from CAQM.",
    l1: [
      { name: "% MRS deployed", num: 115, den: 194,
        formula: "No. of MRS deployed ÷ No. of additional MRS needed",
        rationale: "Assesses the procurement process for different road widths.", agency: "ULB", source: "To be sought from CAQM",
        numL: "deployed", denL: "MRS needed",
        context: ["Additional MRS needed", "MRS procured", "MRS deployed"], active: 2,
        glossary: "MRS — Mechanical Road Sweeper. ULB — Urban Local Body." },
      { name: "% route covered (km)", num: 120764, den: 5104896,
        formula: "Route length covered through MRS ÷ Total target route length to be covered by MRS",
        rationale: "Measures execution of planned sweeping coverage.", agency: "ULB", source: "To be sought from CAQM",
        numL: "km covered", denL: "km targeted",
        context: ["MRS deployed", "Route swept", "Target route covered"], active: 2,
        glossary: "Tracked by road width: above 15 m, 10–15 m and below 10 m." }
    ],
    stages: [
      { n: 1, label: "Tender", hint: "ULB issues tender for the additional MRS needed" },
      { n: 2, label: "Work order", hint: "Work order awarded against the tender issued" },
      { n: 3, label: "Procurement", hint: "MRS delivered against the work order awarded" },
      { n: 4, label: "Sweeping", hint: "Route length swept with MRS fins touching the ground" }
    ],
    metrics: [
      { stage: 1, stageLabel: "Tender", name: "% MRS in tender", num: 168, den: 194,
        formula: "No. of MRS for which tender is live ÷ No. of additional MRS needed",
        rationale: "Tracks the tender process for different road widths.", agency: "ULB", source: "To be sought from CAQM",
        numL: "in tender", denL: "MRS needed",
        context: ["Additional MRS assessed", "Tender live", "Work order awarded"], active: 1 },
      { stage: 2, stageLabel: "Work order", name: "% MRS with work order awarded", num: 142, den: 168,
        formula: "MRS for which work order awarded ÷ MRS for which tender issued",
        rationale: "Measures progress from tendering to award of work.", agency: "ULB", source: "To be sought from CAQM",
        numL: "awarded", denL: "tenders issued",
        context: ["Tender issued", "Work order awarded", "MRS delivered"], active: 1 },
      { stage: 3, stageLabel: "Procurement", name: "% MRS procurement completed (MRS delivered)", num: 115, den: 142,
        formula: "MRS for which procurement completed ÷ MRS for which work order awarded",
        rationale: "Tracks conversion of awards into machines on the ground.", agency: "ULB", source: "To be sought from CAQM",
        numL: "delivered", denL: "work orders awarded",
        context: ["Work order awarded", "MRS delivered", "MRS deployed"], active: 1 },
      { stage: 4, stageLabel: "Sweeping", name: "% of road length swept with MRS fins touching ground", num: 74860, den: 120764,
        formula: "Route length swept with fins touching ground ÷ Route length swept",
        rationale: "Measures cleaning effectiveness and machine productivity.", agency: "ULB", source: "To be sought from CAQM",
        numL: "km effective", denL: "km swept",
        context: ["MRS deployed", "Route swept", "Fins touching ground"], active: 2,
        glossary: "A sweeper only lifts dust when its fins are in contact with the road." }
    ] },

  { key: "road", name: "Road Repair & Remediation", ministry: "MOHUA", owner: "MoHUA · ULBs · CAQM",
    footNote: "All road repair metrics are reported by ULBs. API feeds to be sought from CAQM.",
    l1: [{ name: "% roads with redevelopment completed", num: 881, den: 3170,
      formula: "Road length redeveloped ÷ Road length identified for repair (basis survey)",
      rationale: "Tracks scheme success rate: end-to-end redevelopment across roads.", agency: "ULBs", source: "To be sought from CAQM",
      numL: "km completed", denL: "km identified",
      context: ["Repair identified", "Work order awarded", "Redevelopment completed"], active: 2,
      glossary: "Road length identified for repair is established by survey; ULBs report progress to CAQM." }],
    stages: [
      { n: 1, label: "Tender", hint: "ULB issues tender for the road length identified for repair" },
      { n: 2, label: "Work order", hint: "Work order awarded against the tender issued" },
      { n: 3, label: "Redevelopment", hint: "Road redevelopment completed against the work order" },
      { n: 4, label: "Quality", hint: "Redeveloped road checked against the CAQM quality framework" }
    ],
    metrics: [
      { stage: 1, stageLabel: "Tender", name: "% roads where tender issued", num: 1965, den: 3170,
        formula: "Road length tendered ÷ Road length identified for repair", rationale: "Track tender process.",
        agency: "ULBs", source: "To be sought from CAQM", numL: "km tendered", denL: "km identified",
        context: ["Road surveyed", "Repair identified", "Tender issued"], active: 2 },
      { stage: 2, stageLabel: "Work order", name: "% roads with work order awarded", num: 1395, den: 1965,
        formula: "Road length awarded ÷ Road length tendered", rationale: "Measures progress from tendering to award of work.",
        agency: "ULBs", source: "To be sought from CAQM", numL: "km awarded", denL: "km tendered",
        context: ["Tender issued", "Work order awarded", "Redevelopment starts"], active: 1 },
      { stage: 3, stageLabel: "Redevelopment", name: "% roads with redevelopment completed", num: 881, den: 1395,
        formula: "Road length redeveloped ÷ Road length awarded", rationale: "Tracks execution against awarded work.",
        agency: "ULBs", source: "To be sought from CAQM", numL: "km completed", denL: "km awarded",
        context: ["Work order awarded", "Redevelopment completed", "Quality checked"], active: 1 },
      { stage: 4, stageLabel: "Quality", name: "% roads meeting quality standards", num: 402, den: 720,
        formula: "Road length meeting CAQM quality standards ÷ Road length surveyed for quality",
        rationale: "Tracks quality as per the CAQM framework to ensure impact.", agency: "ULBs", source: "To be sought from CAQM",
        numL: "km compliant", denL: "km surveyed",
        context: ["Redevelopment completed", "Quality survey", "Meets CAQM standard"], active: 2,
        glossary: "CAQM — Commission for Air Quality Management." }
    ] },

  { key: "scc", name: "SCC setup and operations", ministry: "MOHUA", owner: "MoHUA · ULBs",
    footNote: "Enhancement to be done for all metrics in the Delhi malba portal / 311 app.",
    l1: [{ name: "% SCCs operationalized", num: 109, den: 137,
      formula: "No. of SCCs operationalized ÷ No. of SCCs needed", rationale: "Measures SCCs operationalized.",
      agency: "ULB", source: "To be sought from CAQM", numL: "operational", denL: "SCCs needed",
      context: ["SCCs needed", "Land earmarked", "SCC operationalised"], active: 2,
      glossary: "SCC — Small Collection Centre for malba (construction & demolition waste)." }],
    stages: [
      { n: 1, label: "Land identified", hint: "Land parcels earmarked for the SCCs needed" },
      { n: 2, label: "Operationalised", hint: "SCCs made operational as per SOP safeguards" },
      { n: 3, label: "SOP compliance", hint: "Operational SCCs complying with SOP norms" },
      { n: 4, label: "Intake", hint: "Malba handled by operational SCCs" }
    ],
    metrics: [
      { stage: 1, stageLabel: "Land identified", name: "% SCCs where land identified", num: 141, den: 137,
        formula: "SCC land parcels earmarked ÷ No. of SCCs needed", rationale: "Measures land parcels earmarked across SCCs.",
        agency: "ULB", source: "To be sought from CAQM", numL: "parcels earmarked", denL: "SCCs needed",
        context: ["SCCs needed assessed", "Land parcels earmarked", "SCC operationalised"], active: 1 },
      { stage: 2, stageLabel: "Operationalised", name: "% SCCs operationalized", num: 109, den: 141,
        formula: "No. of SCCs operationalized ÷ SCC land parcels earmarked", rationale: "Measures SCCs operationalized as per SOP safeguards.",
        agency: "ULB", source: "To be sought from CAQM", numL: "operational", denL: "parcels earmarked",
        context: ["Land parcels earmarked", "SCC operationalised", "SOP compliance checked"], active: 1 },
      { stage: 3, stageLabel: "SOP compliance", name: "% compliance with SOP", num: 71, den: 109,
        formula: "No. of SCCs complying with SOP ÷ No. of SCCs operationalized", rationale: "Measures operationalized SCCs complying with norms.",
        agency: "ULB", source: "To be sought from CAQM", numL: "compliant", denL: "operational",
        context: ["SCC operationalised", "SOP audit", "Compliant SCC"], active: 1,
        glossary: "SOP — Standard Operating Procedure issued for SCC siting, handling and safeguards." },
      { stage: 4, stageLabel: "Intake", name: "Intake per SCC", num: 19263, den: 109, rate: true, unit: " T",
        formula: "Monthly malba intake ÷ No. of SCCs operationalized", rationale: "Tracks malba handled by SCCs.",
        agency: "ULB", source: "To be sought from CAQM", numL: "tonnes", denL: "operational SCCs",
        context: ["SCC operationalised", "Malba received", "Intake recorded"], active: 2,
        glossary: "Intake is a rate, not a percentage — it has no target band." }
    ] },

  { key: "iccc", name: "ICCC monitoring of construction sites", ministry: "MOEFCC", owner: "MoEFCC · DPCC / SPCB",
    footNote: "ICCC monitoring is live in Delhi; other states are yet to onboard.",
    l1: [{ name: "% sites complying with identified interventions", num: 726, den: 1842,
      formula: "Technically compliant sites (registered, camera & self audit app deployed) ÷ Total sites",
      rationale: "Monitors registered sites that have deployed dust mitigation interventions.",
      agency: "DPCC / SPCB", source: "Available on dust portal", numL: "technically compliant", denL: "total sites",
      context: ["Total sites", "Registered on portal", "Camera & self audit app deployed"], active: 2,
      glossary: "ICCC — Integrated Command and Control Centre." }],
    stages: [
      { n: 1, label: "Site registration", hint: "Sites registered on the dust portal and complying with interventions" },
      { n: 2, label: "Enforcement", hint: "Inspections conducted and environmental compensation imposed" }
    ],
    metrics: [
      { stage: 1, stageLabel: "Site registration", name: "Share of sites registered", num: 1190, den: 1842,
        formula: "Sites registered on portal ÷ Total sites", rationale: "Measures integration of sites with the ICCC for real-time monitoring.",
        agency: "DPCC / SPCB", source: "Available on dust portal", numL: "registered", denL: "total sites",
        context: ["Total sites", "Registered on portal", "Interventions deployed"], active: 1 },
      { stage: 1, stageLabel: "Site registration", name: "% sites complying with interventions", num: 726, den: 1190,
        formula: "Sites with camera linkage & self audit app ÷ Sites registered on portal",
        rationale: "Measures number of sites complying with norms.", agency: "DPCC / SPCB", source: "Available on dust portal",
        numL: "compliant", denL: "registered",
        context: ["Registered on portal", "Camera linked & self audit app", "Monitored live"], active: 1 },
      { stage: 1, stageLabel: "Site registration", name: "% compliance with dust norms", num: 655, den: 1190,
        formula: "Sites compliant with dust norms ÷ Sites registered on portal", rationale: "Monitors whether sites are actually controlling dust.",
        agency: "DPCC / SPCB", source: "Available on dust portal", numL: "compliant", denL: "registered",
        context: ["Registered on portal", "Dust norms checked", "Compliant site"], active: 1 },
      { stage: 2, stageLabel: "Enforcement", name: "% of sites with EC imposed", num: 118, den: 430,
        formula: "No. of sites with EC imposed ÷ No. of inspections conducted", rationale: "Monitors penalizations done on inspected sites.",
        agency: "DPCC / SPCB", source: "Not yet identified", numL: "with EC imposed", denL: "inspections",
        context: ["Violation detected", "Inspection conducted", "EC imposed"], active: 2,
        glossary: "EC — Environmental Compensation, imposed on a site found in violation." }
    ] },

  { key: "greening", name: "Greening", ministry: "MOHUA", owner: "MoEFCC · State forest depts.",
    footNote: "Plantation and area figures are reported by state greening agencies.",
    l1: [{ name: "% target area greened", num: 964, den: 4340,
      formula: "Actual target area greened ÷ Target area to be greened",
      rationale: "Tracks success of the initiative via actual area greened out of target.",
      agency: "State greening agencies", source: "Source to be confirmed", numL: "hectares greened", denL: "hectares targeted",
      context: ["Target area set", "Plantation done", "Area greened"], active: 2 }],
    stages: [{ n: 1, label: "Plantation", hint: "Trees, shrubs and bamboo planted against the plantation target" }],
    metrics: [
      { stage: 1, stageLabel: "Plantation", name: "% plantation target achieved", num: 594600, den: 2178000,
        formula: "Actual plantations (shrubs, trees and bamboos) ÷ Target plantation",
        rationale: "Tracks number of plantations done out of target.", agency: "State greening agencies", source: "To be sought from CAQM",
        numL: "planted", denL: "target plantations",
        context: ["Plantation target set", "Plantation done", "Area greened"], active: 1,
        glossary: "Actual plantations count trees, shrubs and bamboo together against a single plantation target." }
    ] },

  { key: "cems", name: "CEMS and APCD for industries", ministry: "MOEFCC", owner: "MoEFCC · SPCB · NCRPB",
    splits: [{ key: "apcd", label: "APCD scheme", mult: 1 }, { key: "ocems", label: "OCEMS installation", mult: 1 }],
    footNote: "APCD and OCEMS are tracked as two schemes on the same industrial base.",
    l1: [
      { seg: "apcd", name: "% APCD installations completed", num: 327, den: 2115,
        formula: "Units with APCD installed (certificate uploaded) ÷ (Total target − Units exempted)",
        rationale: "Monitor implementation progress.", agency: "SPCB", source: "APCD Portal",
        numL: "installed", denL: "eligible units",
        context: ["Target industries", "Approval issued", "APCD installed"], active: 2,
        glossary: "APCD — Air Pollution Control Device. Exempted units are excluded from the target." },
      { seg: "ocems", name: "% industries with no red alerts", num: 2142, den: 2357,
        formula: "Units with no red alerts (as per CPCB norms) ÷ Total target industries",
        rationale: "Identify compliant units for regulatory intervention.", agency: "SPCB", source: "OCEMS Portal",
        numL: "with no red alert", denL: "target industries",
        context: ["Target industries", "OCEMS active", "No red alert"], active: 2,
        glossary: "A red alert is triggered when the 50 mg/Nm³ norm is exceeded, the system is offline, or a static value is reported." }
    ],
    stages: [
      { n: 1, label: "Application", hint: "Industrial units register on the APCD portal" },
      { n: 2, label: "Screening & approval", hint: "SAC review and SPCB approval of installation applications" },
      { n: 3, label: "Installation", hint: "APCD installed and documents uploaded" },
      { n: 4, label: "Technical approval", hint: "SPCB financial approval on submitted installations" },
      { n: 5, label: "Financial sanction", hint: "NCRPB releases payment via PFMS" },
      { n: 6, label: "OCEMS", hint: "OCEMS installation and red alert compliance" }
    ],
    metrics: [
      { seg: "apcd", stage: 1, stageLabel: "Application", name: "Share of industries registered on portal", num: 1323, den: 2115,
        formula: "Units registered on portal ÷ (Target industrial units − Units exempted)", rationale: "Track scheme adoption.",
        agency: "SPCB", source: "APCD Portal", numL: "registered", denL: "eligible units",
        context: ["Target industries", "Registered on portal", "Application submitted"], active: 1 },
      { seg: "apcd", stage: 2, stageLabel: "Screening & approval", name: "% installation applications approved (post SAC and SPCB)", num: 666, den: 1149,
        formula: "Approved applications (SAC reviewed, SPCB approval issued) ÷ Total applications submitted",
        rationale: "Track initiation of installation.", agency: "SPCB, SAC", source: "APCD Portal",
        numL: "approved", denL: "applications",
        context: ["Application submitted", "SAC review", "SPCB approval issued"], active: 2,
        glossary: "SAC — Scheme Approval Committee, which reviews applications before SPCB issues approval." },
      { seg: "apcd", stage: 2, stageLabel: "Screening & approval", name: "% applications rejected", num: 203, den: 1149, invert: true,
        formula: "Applications rejected ÷ Total applications submitted", rationale: "Track applications rejected.",
        agency: "SAC, SPCB", source: "APCD Portal", numL: "rejected", denL: "applications",
        context: ["Application submitted", "SAC / SPCB screening", "Rejected"], active: 2,
        glossary: "A lower figure is better here — the status band is inverted." },
      { seg: "apcd", stage: 3, stageLabel: "Installation", name: "Share of APCD installations out of approved applications", num: 327, den: 666,
        formula: "Units with APCD installed ÷ Applications approved", rationale: "Monitor implementation progress.",
        agency: "SPCB", source: "APCD Portal", numL: "installed", denL: "approved applications",
        context: ["Approval issued", "APCD installed", "Documents uploaded"], active: 1 },
      { seg: "apcd", stage: 4, stageLabel: "Technical approval", name: "% financial approvals completed by SPCB", num: 162, den: 298,
        formula: "Installations with SPCB financial approval ÷ Installations that submitted documents",
        rationale: "Detect SPCB verification and approval rate.", agency: "SPCB", source: "APCD Portal",
        numL: "approved", denL: "installations submitted",
        context: ["Installation completed", "Documents submitted", "SPCB financial approval"], active: 2 },
      { seg: "apcd", stage: 5, stageLabel: "Financial sanction", name: "% payments released by NCRPB", num: 101, den: 666,
        formula: "Units with payment released by NCRPB ÷ Applications approved by SPCB", rationale: "Monitor sanction rate.",
        agency: "NCRPB", source: "APCD Portal, PFMS", numL: "paid", denL: "approved by SPCB",
        context: ["SPCB approval", "NCRPB sanction", "Payment released via PFMS"], active: 2 }, 
      { seg: "ocems", stage: 6, stageLabel: "OCEMS", name: "% industries with OCEMS installed", num: 2295, den: 2357,
        formula: "Units with OCEMS installed ÷ Total target industries", rationale: "Track implementation progress.",
        agency: "Industry / SPCB", source: "OCEMS Portal", numL: "installed", denL: "target industries",
        context: ["Target industries", "OCEMS installed", "Live data uploaded"], active: 1,
        glossary: "OCEMS — Online Continuous Emission Monitoring System." },
      { seg: "ocems", stage: 6, stageLabel: "OCEMS", name: "% industries with no red alerts", num: 2142, den: 2295,
        formula: "Units with no red alerts ÷ Total industries with active OCEMS", rationale: "Identify compliant units for regulatory intervention.",
        agency: "SPCB", source: "OCEMS Portal", numL: "with no red alert", denL: "active OCEMS",
        context: ["OCEMS active", "CPCB norms applied", "No red alert"], active: 2 }
    ] }
];

export const MINISTRIES = [
  { key: "MORTH", full: "Ministry of Road Transport and Highways" },
  { key: "MOHUA", full: "Ministry of Housing and Urban Affairs" },
  { key: "MOEFCC", full: "Ministry of Environment, Forest and Climate Change" }
];

export const NAV = [
  { key: "summary", label: "All initiatives — Summary" },
  { key: "parivartan", label: "PARIVARTAN" },
  { key: "green-contribution", label: "Green Contribution" },
  { key: "mrs", label: "Mechanized Road Sweeping" },
  { key: "road", label: "Road Repair & Remediation" },
  { key: "scc", label: "SCC setup and operations" },
  { key: "greening", label: "Greening" },
  { key: "iccc", label: "ICCC monitoring of large construction sites" },
  { key: "cems", label: "Installation of CEMS and APCD for industries" }
];

/* Per-state split of each NCR roll-up: [share of denominator, relative performance].
   State figures are derived from these weights and always sum back to the NCR total. */
export const REGIONS = ["Delhi", "UP", "Rajasthan", "Haryana"];
export const REGION_W = {
  parivartan: [[0.27, 1.25], [0.38, 0.95], [0.13, 0.68], [0.22, 1.05]],
  "green-contribution": [[0.25, 1], [0.25, 1], [0.25, 1], [0.25, 1]],
  mrs: [[0.43, 1.30], [0.24, 0.75], [0.07, 0.15], [0.26, 0.90]],
  road: [[0.40, 1.25], [0.28, 0.80], [0.11, 0.20], [0.21, 1.00]],
  scc: [[0.44, 1.90], [0.24, 0.10], [0.09, 0.10], [0.23, 0.12]],
  iccc: [[1, 1], [0, 0], [0, 0], [0, 0]],
  greening: [[0.28, 1.35], [0.33, 0.85], [0.18, 0.45], [0.21, 1.10]],
  cems: [[0.20, 1.40], [0.37, 0.75], [0.18, 0.45], [0.25, 1.00]]
};

export function regionSlice(def, key, region) {
  const idx = REGIONS.indexOf(region);
  const w = REGION_W[key];
  if (idx < 0 || !w) return { num: def.num, den: def.den };
  const dens = w.map((x, i) => (i === w.length - 1 ? null : Math.round(def.den * x[0])));
  dens[dens.length - 1] = def.den - dens.slice(0, -1).reduce((a, b) => a + b, 0);
  const raw = w.map((x, i) => Math.max(0, dens[i]) * x[1]);
  const tot = raw.reduce((a, b) => a + b, 0);
  const scale = tot > 0 ? def.num / tot : 0;
  const nums = raw.map((r, i) => Math.min(Math.max(0, dens[i]), Math.round(r * scale)));
  return { num: nums[idx], den: Math.max(0, dens[idx]) };
}

/* ---- derived views -------------------------------------------------- */

export function rangeFactor(from, to) {
  const days = Math.max(1, Math.round((new Date(to) - new Date(from)) / 86400000) + 1);
  return { days, factor: Math.min(1, 0.42 + 0.58 * (days / 192)) };
}

export function metricView(def, id, key, region, rf) {
  const sl = region && region !== "All-Delhi NCR" ? regionSlice(def, key, region) : { num: def.num, den: def.den };
  const num = Math.round(sl.num * rf);
  const den = sl.den;
  const has = den > 0;
  if (def.rate) {
    const v = has ? Math.round(num / den) : 0;
    return { ...def, id, raw: 100,
      pct: has ? nf(v) + (def.unit || "") : "\u2014",
      frac: has ? nf(num) + " / " + nf(den) : "no data",
      fracLong: has ? nf(num) + " " + def.numL + " across " + nf(den) + " " + def.denL : "no data in range",
      bar: "0%", flag: "#5A5C5E", track: "#EDEDE8", status: has ? "Rate \u2014 no target band" : "No data" };
  }
  const p = has ? Math.round((num / den) * 100) : 0;
  const band = def.invert ? 100 - p : p;
  return { ...def, id, raw: band, den,
    pct: has ? p + "%" : "\u2014",
    frac: has ? nf(num) + " / " + nf(den) : "no data",
    fracLong: has ? nf(num) + " " + def.numL + " of " + nf(den) + " " + def.denL : "no data in range",
    bar: (has ? Math.min(100, p) : 0) + "%",
    flag: has ? flag(band) : "#C4C4BE",
    track: has ? track(band) : "#EDEDE8",
    status: has ? statusWord(band) : "No data" };
}

/* A segment either selects rows tagged with it, or rescales untagged rows by its
   share of the base (mult) and its relative performance (perf). */
export function segApply(defs, ini, segKey) {
  if (!ini.splits) return defs;
  const cur = ini.splits.find((v) => v.key === segKey) || ini.splits[0];
  const tagged = defs.some((x) => x.seg);
  return defs.filter((x) => !x.seg || x.seg === cur.key).map((x) => {
    if (x.seg || tagged) return x;
    const den = Math.round(x.den * cur.mult);
    return { ...x, den, num: Math.min(den, Math.round(x.num * cur.mult * (cur.perf || 1))) };
  });
}

// raw = every segment together, used by the tile levels
export const l1Of = (ini, region, rf, seg, raw) =>
  (raw ? ini.l1 : segApply(ini.l1, ini, seg)).map((d, i) => metricView(d, "L1-" + i, ini.key, region, rf));
export const l2Of = (ini, region, rf, seg, raw) =>
  (raw ? ini.metrics : segApply(ini.metrics, ini, seg)).map((d, i) => metricView(d, "L2-" + i, ini.key, region, rf));

export const PRESETS = [
  { label: "Last 30 days", from: "2026-07-13", to: "2026-08-11" },
  { label: "Last 90 days", from: "2026-05-14", to: "2026-08-11" },
  { label: "FY to date", from: "2026-04-01", to: "2026-08-11" },
  { label: "Since launch", from: "2026-02-01", to: "2026-08-11" }
];

export function fmtDate(v) {
  const d = new Date(v + "T00:00:00");
  return d.getDate() + " " + d.toLocaleString("en-IN", { month: "short" }) + " " + d.getFullYear();
}
